<a href="https://colab.research.google.com/github/dmarinere/DSN-Bootcamp/blob/master/My_work_with_DSN_Hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# Input data files are available in the "../input/" directory.
import os
import matplotlib.pyplot as plt#visualization
%matplotlib inline
import pandas as pd
import seaborn as sns#visualization
import itertools
import warnings
warnings.filterwarnings("ignore")
import io
import plotly.offline as py#visualization
py.init_notebook_mode(connected=True)#visualization
import plotly.graph_objs as go#visualization
import plotly.tools as tls#visualization
import plotly.figure_factory as ff#visualization

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
cd /content/drive/My Drive/DSN-AI-Bootcamp

/content/drive/My Drive/DSN-AI-Bootcamp

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
train = pd.read_csv("./Train.csv")
test = pd.read_csv("./Test.csv")
submission = pd.read_csv('./SampleSubmission.csv')

In [ ]:
test_id = test['Applicant_ID']

In [ ]:
print ("Rows     : " ,train.shape[0])
print ("Columns  : " ,train.shape[1])
print ("\nFeatures : \n" ,train.columns.tolist())
print ("\nMissing values :  ", train.isnull().sum().values.sum())
print ("\nUnique values :  \n",train.nunique())

Rows     :  56000
Columns  :  52

Features :
 ['Applicant_ID', 'form_field1', 'form_field2', 'form_field3', 'form_field4', 'form_field5', 'form_field6', 'form_field7', 'form_field8', 'form_field9', 'form_field10', 'form_field11', 'form_field12', 'form_field13', 'form_field14', 'form_field15', 'form_field16', 'form_field17', 'form_field18', 'form_field19', 'form_field20', 'form_field21', 'form_field22', 'form_field23', 'form_field24', 'form_field25', 'form_field26', 'form_field27', 'form_field28', 'form_field29', 'form_field30', 'form_field31', 'form_field32', 'form_field33', 'form_field34', 'form_field35', 'form_field36', 'form_field37', 'form_field38', 'form_field39', 'form_field40', 'form_field41', 'form_field42', 'form_field43', 'form_field44', 'form_field45', 'form_field46', 'form_field47', 'form_field48', 'form_field49', 'form_field50', 'default_status']

Missing values :   528773

Unique values :
 Applicant_ID      56000
form_field1         449
form_field2       20015
form_field3       14617
form_field4        2927
form_field5        2991
form_field6        5846
form_field7       23199
form_field8       12820
form_field9       22650
form_field10      30942
form_field11       9508
form_field12      16778
form_field13      21960
form_field14       1237
form_field15      23783
form_field16         11
form_field17         15
form_field18         16
form_field19         26
form_field20         27
form_field21      11101
form_field22      23583
form_field23      16619
form_field24      12571
form_field25       5014
form_field26        594
form_field27        558
form_field28         95
form_field29        654
form_field30        274
form_field31        394
form_field32       2620
form_field33        554
form_field34         18
form_field35         11
form_field36         66
form_field37         52
form_field38         58
form_field39         15
form_field40       9848
form_field41      14375
form_field42        986
form_field43         59
form_field44      33238
form_field45          6
form_field46          6
form_field47          2
form_field48      32115
form_field49      13207
form_field50      44746
default_status        2
dtype: int64

In [ ]:
train.isnull().sum()

Applicant_ID      0
form_field1       0
form_field2       0
form_field3       0
form_field4       0
form_field5       0
form_field6       0
form_field7       0
form_field8       0
form_field9       0
form_field10      0
form_field11      0
form_field12      0
form_field13      0
form_field14      0
form_field15      0
form_field16      0
form_field17      0
form_field18      0
form_field19      0
form_field20      0
form_field21      0
form_field22      0
form_field23      0
form_field24      0
form_field25      0
form_field26      0
form_field27      0
form_field28      0
form_field29      0
form_field30      0
form_field31      0
form_field32      0
form_field33      0
form_field34      0
form_field35      0
form_field36      0
form_field37      0
form_field38      0
form_field39      0
form_field40      0
form_field41      0
form_field42      0
form_field43      0
form_field44      0
form_field45      0
form_field46      0
form_field47      0
form_field48      0
form_field49      0
form_field50      0
default_status    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_recall_curve, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [ ]:
train

        Applicant_ID  form_field1  ...  form_field50  default_status
0      Apcnt_1000000       3436.0  ...      0.044335              no
1      Apcnt_1000004       3456.0  ...      0.322436              no
2      Apcnt_1000008       3276.0  ...      0.011640             yes
3      Apcnt_1000012       3372.0  ...      0.082729              no
4      Apcnt_1000016       3370.0  ...      0.045630              no
...              ...          ...  ...           ...             ...
55995   Apcnt_999968       3740.0  ...      0.241598              no
55996   Apcnt_999972       3360.0  ...           NaN             yes
55997   Apcnt_999980       3500.0  ...      0.163153              no
55998   Apcnt_999988       3280.0  ...      0.002997              no
55999   Apcnt_999996       3522.0  ...      0.678245              no

[56000 rows x 52 columns]

In [ ]:
test

        Applicant_ID  form_field1  ...  form_field49  form_field50
0      Apcnt_1000032       3236.0  ...      0.000000      0.011221
1      Apcnt_1000048       3284.0  ...      0.504974      0.043525
2      Apcnt_1000052          NaN  ...      0.000000           NaN
3      Apcnt_1000076       3232.0  ...      0.788809      0.104029
4      Apcnt_1000080       3466.0  ...      1.637733      0.163124
...              ...          ...  ...           ...           ...
23995   Apcnt_999940       3258.0  ...      0.000000           NaN
23996   Apcnt_999956       3514.0  ...      3.000000      0.930931
23997   Apcnt_999976       3302.0  ...      4.855060           NaN
23998   Apcnt_999984       3334.0  ...      0.818733      0.023749
23999   Apcnt_999992       3324.0  ...      0.000000      0.391927

[24000 rows x 51 columns]

In [ ]:
dropcols = ['Applicant_ID', 'default_status']
y = train['default_status'] # labels
x = train.drop(columns=dropcols, axis=1)
test = test.drop(columns=['Applicant_ID'], axis=1) #will use this for predicting and submitting the resulting
print(x.shape)
print(y.shape)
print(test.shape)

(56000, 50)
(56000,)
(24000, 50)

In [ ]:
pip install catboost

Collecting catboost
  Downloading https://files.pythonhosted.org/packages/90/86/c3dcb600b4f9e7584ed90ea9d30a717fb5c0111574675f442c3e7bc19535/catboost-0.24.1-cp36-none-manylinux1_x86_64.whl (66.1MB)
     |████████████████████████████████| 66.1MB 42kB/s
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.0.5)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.18.5)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly->catboost) (1.3.3)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Installing collected packages: catboost
Successfully installed catboost-0.24.1

In [ ]:
from catboost import CatBoostClassifier

In [ ]:
cate_features_index=np.where(x.dtypes != float) [0]; cate_features_index

array([13, 46])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score, log_loss
errcb=[]
y_pred_totcb=[]
from sklearn.model_selection import KFold,StratifiedKFold, TimeSeriesSplit, GroupKFold
fold=StratifiedKFold(n_splits=5,shuffle=True, random_state=12345)
i=1
for train_index, test_index in fold.split(x,y):
    X_train, X_test = x.iloc[train_index], x.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    m=CatBoostClassifier(n_estimators=10000, max_depth=6,  bootstrap_type='Bernoulli',
                              subsample=0.9,
                              eval_metric='AUC',
                              metric_period=20,)
    m.fit(X_train,y_train,cat_features=cate_features_index,eval_set=[(X_train, y_train),(X_test, y_test)],verbose=100, early_stopping_rounds=200)#,verbose=100)
    preds=m.predict_proba(X_test)[:, 1]
    print("err: ",log_loss(y_test,preds))
    print("err: ",roc_auc_score(y_test,preds))
    errcb.append(log_loss(y_test,preds))
    p = m.predict_proba(test)[:, 1]
    y_pred_totcb.append(p)

Learning rate set to 0.02977

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

0:	test: 0.7881717	test1: 0.7904327	best: 0.7904327 (0)	total: 121ms	remaining: 20m 11s
100:	test: 0.8374650	test1: 0.8327614	best: 0.8327614 (100)	total: 5.84s	remaining: 9m 32s
200:	test: 0.8450026	test1: 0.8369731	best: 0.8369731 (200)	total: 11.3s	remaining: 9m 11s
300:	test: 0.8504026	test1: 0.8391070	best: 0.8391116 (299)	total: 16.8s	remaining: 9m 1s
400:	test: 0.8553364	test1: 0.8405245	best: 0.8405245 (400)	total: 22.2s	remaining: 8m 51s
500:	test: 0.8608873	test1: 0.8413300	best: 0.8413300 (500)	total: 27.6s	remaining: 8m 42s
600:	test: 0.8661020	test1: 0.8419275	best: 0.8419457 (588)	total: 33s	remaining: 8m 35s
700:	test: 0.8705087	test1: 0.8423261	best: 0.8423261 (700)	total: 38.3s	remaining: 8m 28s
800:	test: 0.8748447	test1: 0.8424646	best: 0.8425360 (787)	total: 43.6s	remaining: 8m 21s
900:	test: 0.8790221	test1: 0.8425762	best: 0.8425798 (891)	total: 49s	remaining: 8m 14s
1000:	test: 0.8828308	test1: 0.8425625	best: 0.8426267 (912)	total: 54.3s	remaining: 8m 7s
1100:	test: 0.8866231	test1: 0.8427403	best: 0.8427614 (1096)	total: 59.5s	remaining: 8m 1s
1200:	test: 0.8904546	test1: 0.8428685	best: 0.8428987 (1196)	total: 1m 4s	remaining: 7m 54s
1300:	test: 0.8939534	test1: 0.8430560	best: 0.8431107 (1280)	total: 1m 9s	remaining: 7m 47s
1400:	test: 0.8973070	test1: 0.8430516	best: 0.8431123 (1313)	total: 1m 15s	remaining: 7m 42s
1500:	test: 0.9006624	test1: 0.8431550	best: 0.8432454 (1463)	total: 1m 20s	remaining: 7m 36s
1600:	test: 0.9037651	test1: 0.8431717	best: 0.8432454 (1463)	total: 1m 25s	remaining: 7m 30s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.843245371
bestIteration = 1463

Shrink model to first 1464 iterations.
err:  0.4029430710012007
err:  0.8432453710307609
Learning rate set to 0.02977
0:	test: 0.7890721	test1: 0.7859398	best: 0.7859398 (0)	total: 60.9ms	remaining: 10m 9s

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

100:	test: 0.8372052	test1: 0.8325386	best: 0.8325386 (100)	total: 5.54s	remaining: 9m 3s
200:	test: 0.8450141	test1: 0.8370968	best: 0.8370968 (200)	total: 10.9s	remaining: 8m 50s
300:	test: 0.8505414	test1: 0.8394783	best: 0.8394788 (298)	total: 16.2s	remaining: 8m 40s
400:	test: 0.8557577	test1: 0.8408487	best: 0.8408487 (400)	total: 21.4s	remaining: 8m 32s
500:	test: 0.8612992	test1: 0.8416336	best: 0.8416336 (500)	total: 26.6s	remaining: 8m 24s
600:	test: 0.8664668	test1: 0.8417922	best: 0.8417922 (600)	total: 31.8s	remaining: 8m 18s
700:	test: 0.8713765	test1: 0.8423743	best: 0.8423743 (700)	total: 37.1s	remaining: 8m 12s
800:	test: 0.8757350	test1: 0.8426237	best: 0.8426491 (753)	total: 42.3s	remaining: 8m 5s
900:	test: 0.8800809	test1: 0.8428035	best: 0.8428035 (900)	total: 47.5s	remaining: 7m 59s
1000:	test: 0.8839492	test1: 0.8429353	best: 0.8429782 (997)	total: 52.7s	remaining: 7m 53s
1100:	test: 0.8879585	test1: 0.8428980	best: 0.8429928 (1018)	total: 57.8s	remaining: 7m 47s
1200:	test: 0.8916734	test1: 0.8429301	best: 0.8429928 (1018)	total: 1m 3s	remaining: 7m 41s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8429927797
bestIteration = 1018

Shrink model to first 1019 iterations.
err:  0.4038913253467282
err:  0.842992779711962
Learning rate set to 0.02977
0:	test: 0.7882942	test1: 0.7902886	best: 0.7902886 (0)	total: 63.4ms	remaining: 10m 33s

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

100:	test: 0.8373552	test1: 0.8348394	best: 0.8348394 (100)	total: 5.45s	remaining: 8m 54s
200:	test: 0.8448941	test1: 0.8390671	best: 0.8390671 (200)	total: 10.6s	remaining: 8m 36s
300:	test: 0.8503858	test1: 0.8409205	best: 0.8409205 (300)	total: 15.7s	remaining: 8m 27s
400:	test: 0.8555410	test1: 0.8421406	best: 0.8421406 (400)	total: 20.9s	remaining: 8m 21s
500:	test: 0.8610963	test1: 0.8430142	best: 0.8430603 (499)	total: 26.1s	remaining: 8m 14s
600:	test: 0.8664743	test1: 0.8433452	best: 0.8433706 (578)	total: 31.2s	remaining: 8m 8s
700:	test: 0.8713222	test1: 0.8438361	best: 0.8438361 (700)	total: 36.4s	remaining: 8m 3s
800:	test: 0.8758313	test1: 0.8440421	best: 0.8440421 (800)	total: 41.6s	remaining: 7m 57s
900:	test: 0.8801743	test1: 0.8441580	best: 0.8442082 (849)	total: 46.7s	remaining: 7m 51s
1000:	test: 0.8842908	test1: 0.8441994	best: 0.8442511 (966)	total: 51.9s	remaining: 7m 46s
1100:	test: 0.8881334	test1: 0.8439515	best: 0.8442511 (966)	total: 57.1s	remaining: 7m 41s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8442511022
bestIteration = 966

Shrink model to first 967 iterations.
err:  0.4020440497169176
err:  0.8442511021960897
Learning rate set to 0.02977
0:	test: 0.7904627	test1: 0.7812700	best: 0.7812700 (0)	total: 63.9ms	remaining: 10m 38s

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

100:	test: 0.8387870	test1: 0.8283362	best: 0.8283362 (100)	total: 5.6s	remaining: 9m 8s
200:	test: 0.8467671	test1: 0.8317901	best: 0.8317901 (200)	total: 11s	remaining: 8m 54s
300:	test: 0.8523851	test1: 0.8329017	best: 0.8329299 (299)	total: 16.4s	remaining: 8m 48s
400:	test: 0.8575805	test1: 0.8340154	best: 0.8340154 (400)	total: 21.8s	remaining: 8m 42s
500:	test: 0.8635528	test1: 0.8343983	best: 0.8344226 (498)	total: 27.1s	remaining: 8m 34s
600:	test: 0.8689926	test1: 0.8348255	best: 0.8348480 (599)	total: 32.3s	remaining: 8m 25s
700:	test: 0.8737434	test1: 0.8351269	best: 0.8351269 (700)	total: 37.6s	remaining: 8m 19s
800:	test: 0.8783851	test1: 0.8351543	best: 0.8351543 (800)	total: 42.9s	remaining: 8m 12s
900:	test: 0.8827729	test1: 0.8352305	best: 0.8352891 (886)	total: 48.2s	remaining: 8m 7s
1000:	test: 0.8870250	test1: 0.8354052	best: 0.8354844 (984)	total: 53.7s	remaining: 8m 2s
1100:	test: 0.8909689	test1: 0.8353769	best: 0.8354987 (1064)	total: 59.3s	remaining: 7m 59s
1200:	test: 0.8945135	test1: 0.8352560	best: 0.8354987 (1064)	total: 1m 4s	remaining: 7m 53s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8354986697
bestIteration = 1064

Shrink model to first 1065 iterations.
err:  0.4094521048587194
err:  0.8354986696656039
Learning rate set to 0.02977
0:	test: 0.7886315	test1: 0.7877291	best: 0.7877291 (0)	total: 65.9ms	remaining: 10m 59s

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

100:	test: 0.8383869	test1: 0.8311279	best: 0.8311279 (100)	total: 5.56s	remaining: 9m 4s
200:	test: 0.8456326	test1: 0.8352195	best: 0.8352195 (200)	total: 10.9s	remaining: 8m 50s
300:	test: 0.8511633	test1: 0.8371845	best: 0.8371845 (300)	total: 16.1s	remaining: 8m 38s
400:	test: 0.8562901	test1: 0.8383257	best: 0.8383257 (400)	total: 21.3s	remaining: 8m 29s
500:	test: 0.8618506	test1: 0.8387206	best: 0.8387378 (499)	total: 26.3s	remaining: 8m 19s
600:	test: 0.8668072	test1: 0.8391725	best: 0.8391924 (592)	total: 31.5s	remaining: 8m 13s
700:	test: 0.8716803	test1: 0.8392861	best: 0.8393604 (693)	total: 36.9s	remaining: 8m 9s
800:	test: 0.8762754	test1: 0.8393918	best: 0.8394342 (760)	total: 42.2s	remaining: 8m 4s
900:	test: 0.8807009	test1: 0.8396148	best: 0.8396372 (869)	total: 47.4s	remaining: 7m 58s

In [ ]:
d = {"Applicant_ID": test_id, 'default_status': np.mean(y_pred_totcb, 0)}
test_predictions = pd.DataFrame(data=d)
test_predictions = test_predictions[["Applicant_ID", 'default_status']]

In [ ]:
test_predictions.to_csv('25kfoldwith2train.csv', index=False)